### ISSUE TITLE
error compiled

### ISSUE THREAD

**Issue by radioham777** [piersfinlayson/otb-iot#42]
Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-38-generic i686)
[make_error1.txt](https://github.com/piersfinlayson/otb-iot/files/2518514/make_error1.txt)

**Comment by piersfinlayson** [comment]
This is essentially related to #41 - from some recent version on rwards the SDK started including function prototypes for the fns I had otbiot had its own (conflicting) definitions for.  It's a trivial fix to get it to compile, but it'll still fail the link step because of the problems in #41.  I'm still figuring out how to fix that properly - taking the new linker file from the SDK seems to leave a non booting ESP :-(.

**Comment by piersfinlayson** [comment]
Fixed in master - have checked it builds and runs with SDK 2.1.0-18-g61248df, on both Wemos D1 mini and otb-iot hardware.
